# -*- coding: utf-8 -*-
"""worksheet1-GURKEERAT_SINGH_(1024230065).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ygrNz043zGTLi-YazR4D8oA-rME9OOq

# ***PYTHON WORKSHEET 1 - GURKEERAT SINGH (1024230065)***
"""

#Q1. Print specific format string

def print_poem():
    print("Twinkle, twinkle, little star,")
    print("How I wonder what you are! ")
    print("Up above the world so high,")
    print("Like a diamond in the sky.")
    print("Twinkle, twinkle, little star,")
    print("How I wonder what you are")

print_poem()

#Q2. Reverse first & last name

first = input("Enter your first name: ")
last = input("Enter your last name: ")
print(last, first)

#3. Area of a circle

import math
r = float(input("Enter radius: "))
area = math.pi * r * r
print("Area of circle:", area)

#4. Display first & last colors

color_list = ["Red", "Green", "White", "Black"]
print("First color:", color_list[0])
print("Last color:", color_list[-1])

#5. Compute value of n + nn + nnn

n = int(input("Enter an integer: "))
result = n + int(str(n)*2) + int(str(n)*3)
print("Result:", result)

#6. Accept comma-separated numbers into list & tuple

numbers = input("Enter comma-separated numbers: ")
list = numbers.split(",")
tuple = tuple(list)
print("List:", list)
print("Tuple:", tuple)

#7. Celsius to Fahrenheit

celsius = float(input("Enter temperature in Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print("Temperature in Fahrenheit:", fahrenheit)

#8. Swap two numbers

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Before swapping: a =", a, "b =", b)
a, b = b, a
print("After swapping: a =", a, "b =", b)

#9. Odd or Even

num = int(input("Enter a number: "))
if num % 2 == 0:
    print("Even")
else:
    print("Odd")

#10. Leap year or not

year = int(input("Enter a year: "))
if year % 4 == 0:
    print("Leap year")
else:
    print("Not a leap year")

#11. Euclidean distance

import math

x1, y1 = map(float, input("Enter x1 y1: ").split())
x2, y2 = map(float, input("Enter x2 y2: ").split())
distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
print("Euclidean Distance:", distance)

#12. Check if angles form a triangle

a = int(input("Enter first angle: "))
b = int(input("Enter second angle: "))
c = int(input("Enter third angle: "))

if a + b + c == 180 and a > 0 and b > 0 and c > 0:
    print("It is a triangle")
else:
    print("Not a triangle")

#13. Compound Interest

# Formula: A = P * (1 + r/n)^(n*t)
P = float(input("Enter principal amount: "))
r = float(input("Enter annual interest rate (in %): ")) / 100
t = int(input("Enter time in years: "))
n = int(input("Enter number of times interest compounded per year: "))

A = P * (1 + r/n)**(n*t)
print("Compound Interest:", A - P)
print("Total Amount:", A)

#14. Check if no. is prime or not

num = int(input("Enter a number: "))
if num > 1:
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

#15. Sum of squares (1^2 + 2^2 + ... + N^2)

N = int(input("Enter a positive integer: "))
sum_squares = sum(i*i for i in range(1, n+1))
print("Sum of squares:", sum_squares)