# -*- coding: utf-8 -*-
"""worksheet3-Gurkeerat_Singh_(1024230065).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pXJM0rbGopPqHcXwTILhar7oD5Trot0p

# **PYTHON WORKSHEET 3 - GURKEERAT SINGH (1024230065)**
"""

# Question 1

def difference_17(n):
    if n > 17:
        return 2 * abs(n - 17)
    else:
        return 17 - n
print(difference_17(22))
print(difference_17(14))

# Question 2

def test_range(n):
    return (100 <= n <= 1000) or (n == 2000)
print(test_range(500))
print(test_range(2000))

# Question 3

def reverse_string(s):
    return s[::-1]
print(reverse_string("GURKEERAT"))

# Question 4

def count_case(s):
    upper = sum(1 for c in s if c.isupper())
    lower = sum(1 for c in s if c.islower())
    return upper, lower
print(count_case("GurKeErat siNGh"))

# Question 5

def unique_list(lst):
    return list(set(lst))
print(unique_list([1, 2, 3, 2, 4, 1, 5]))

# Question 6

def even_numbers(lst):
    return [x for x in lst if x % 2 == 0]
print(even_numbers([1, 2, 3, 4, 5, 6, 7, 8, 9]))

# Question 7

def outer_function(a):
    def inner_function(b):
        return b * b
    return inner_function(a)
print(outer_function(8))

# Question 8

def student(name, age):
    return f"Name: {name}, Age: {age}"
print(student.__code__.co_varnames)  # to show argument names

# Question 8

class Student:
    def __init__(self, student_id, student_name, student_class):
        self.student_id = student_id
        self.student_name = student_name
        self.student_class = student_class
    def display(self):
        print("ID:", self.student_id)
        print("Name:", self.student_name)
        print("Class:", self.student_class)
s = Student(1024230065, "GURKEERAT", "RAI")
s.display()

# Question 9

def move_robot(x, y, direction):
    if direction == "up":
        y += 1
    elif direction == "down":
        y -= 1
    elif direction == "left":
        x -= 1
    elif direction == "right":
        x += 1
    return (x, y)
print(move_robot(0, 0, "up"))
print(move_robot(2, 3, "left"))
print(move_robot(5, 5, "down"))
print(move_robot(1, 1, "right"))

# Question 10

def classify_temperature(temp):
    if temp < 15:
        return "Cold"
    elif 15 <= temp <= 30:
        return "Moderate"
    else:
        return "Hot"

print(classify_temperature(13))
print(classify_temperature(22))
print(classify_temperature(39))

# Question 14

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return 3.14 * self.radius * self.radius

    def perimeter(self):
        return 2 * 3.14 * self.radius

c = Circle(5)
print("Area:", c.area())
print("Perimeter:", c.perimeter())

# Question 15

class StringHandler:
    def __init__(self):
        self.text = ""   # store the string
    def get_String(self):
        # accept string from user
        self.text = input("Enter a string: ")
    def print_String(self):
        # print string in upper case
        print(self.text.upper())
obj = StringHandler()
obj.get_String()
obj.print_String()

# Question 16

class Robot:
    def __init__(self, name, task):
        self.name = name
        self.task = task
        self.battery_level = 100
    def perform_task(self):
        if self.battery_level >= 10:
            print(f"{self.name} is performing task: {self.task}")
            self.battery_level -= 10
        else:
            print(f"{self.name} has low battery! Please recharge.")
    def recharge(self):
        self.battery_level = 100
        print(f"{self.name} is fully recharged.")
    def status(self):
        print(f"Robot Name: {self.name}")
        print(f"Current Task: {self.task}")
        print(f"Battery Level: {self.battery_level}%")